version: '3.8'
services:
  web:
    build: ./docker/php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./uploads:/var/www/html/uploads
    environment:
      - DB_HOST=db
      - DB_NAME=university_v4
      - DB_USER=bsu
      - DB_PASS=secret
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_SECURE=${SMTP_SECURE:-tls}
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: university_v4
      MYSQL_USER: bsu
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
      - ./sql/init_v4.sql:/docker-entrypoint-initdb.d/init_v4.sql:ro

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: bsu
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  dbdata:
